### ISSUE TITLE
Geoopt update

### ISSUE THREAD

**Issue by ferrine** [jdieter31/riemannian-nlp#1]
FYI, the code should be updated to keep in sync with 
https://github.com/geoopt/geoopt/pull/77
Write here if any questions

We are in active development stage, but sorry for troubles

**Comment by jdieter31** [comment]
Thanks for the heads up! We ended up implementing our own version of what geoopt does but it was heavily inspired by geoopts code so we will make sure to give credit on publication!

**Comment by ferrine** [comment]
What limitations of geoopt led you this way?

**Comment by jdieter31** [comment]
It was mainly that geoopt had no in-place operations or great support for working with sparse tensors which my application needed. I ended up making a fork of geoopt but it had grown far enough from the original project that it eventually made more sense to condense the features of it and streamline it as just part of the project codebase.

**Comment by ferrine** [comment]
CC @newkozlukov
